version: "3.7"

services:
  load-balancer:
    build: .
    command: sh -c "python3 test.py"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - type: bind 
        source: ./Data
        target: /app/Data
      - type: bind 
        source: ./Model
        target: /app/Model
      - type: bind
        source: ./DataObjects
        target: /app/DataObjects

